"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Flavor {{{

[flavor]
dark  = "nord-dark"
light = "nord-light"

# : }}}


# : Manager {{{

[manager]
cwd = { fg = "#88C0D0" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#EBCB8B", bold = true, italic = true, underline = true }
find_position = { fg = "#B48EAD", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#A3BE8C", bg = "#A3BE8C" }
marker_cut      = { fg = "#BF616A", bg = "#BF616A" }
marker_marked   = { fg = "#8FBCBB", bg = "#8FBCBB" }
marker_selected = { fg = "#EBCB8B", bg = "#EBCB8B" }

# Tab
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# Count
count_copied   = { fg = "#ECEFF4", bg = "#A3BE8C" }
count_cut      = { fg = "#ECEFF4", bg = "#BF616A" }
count_selected = { fg = "#ECEFF4", bg = "#EBCB8B" }

# Border
border_symbol = "│"
border_style  = { fg = "#4C566A" }

# Highlighting
syntect_theme = ""

# : }}}


# : Mode {{{

[mode]

normal_main = { bg = "#5E81AC", bold = true }
normal_alt  = { fg = "#5E81AC", bg = "#3B4252" }

# Select mode
select_main = { bg = "#BF616A", bold = true }
select_alt  = { fg = "#BF616A", bg = "#3B4252" }

# Unset mode
unset_main = { bg = "#BF616A", bold = true }
unset_alt  = { fg = "#BF616A", bg = "#3B4252" }

# : }}}


# : Status bar {{{

[status]
overall   = {}
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep   = { fg = "#4C566A" }
perm_type  = { fg = "#A3BE8C" }
perm_read  = { fg = "#EBCB8B" }
perm_write = { fg = "#BF616A" }
perm_exec  = { fg = "#88C0D0" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#5E81AC", bg = "#2E3440" }
progress_error  = { fg = "#BF616A", bg = "#2E3440" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#EBCB8B" },
    
    # Media
    { mime = "{audio,video}/*", fg = "#B48EAD" },
    
    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#BF616A" },
    
    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#88C0D0" },
    
    # Special files
    { name = "*", is = "orphan", bg = "#BF616A" },
    { name = "*", is = "exec", fg = "#A3BE8C" },
    
    # Fallback
    { name = "*/", fg = "#5E81AC" }
]

# : }}}
